param([string]$TrxPath,[string]$WorkbookPath)
$ErrorActionPreference='Stop'
$map=[ordered]@{AuthenticationAndConnectivityTests=@('AUTH-NET','Authentication and NetBird validation');ConfigSetupWizardTests=@('CONFIG-ID','Configuration identity preservation');SiteSettingsTests=@('SITE-CFG','Site settings and device mapping');EdgeClientCertificateProvisionerTests=@('MTLS-CERT','mTLS client certificate');ExecutionEndpointRegistrationTests=@('ENDPOINT','Kiosk and execution endpoint contracts');PeripheralDeviceRegistrationTests=@('DEVICE','Peripheral device registration contract');EdgeDeploymentApiTests=@('DEPLOY-API','Full Edge deployment command contract');FullEdgeConfigurationInstallerTests=@('LUA-INSTALL','Verified Lua bundle installation');MachinePluginLoaderTests=@('DRIVER-DLL','Peripheral driver plugin loading');OrderRequestTests=@('LOCAL-ORDER','Legacy local Order contract');EdgeOrderInboxTests=@('MTLS-ORDER','mTLS ExecuteOrder validation');EdgeOrderExecutionQueueTests=@('ORDER-QUEUE','Durable production queue');ProductionReportOutboxTests=@('REPORT-OUT','Production report outbox')}
function Kind($n){if($n-match 'Limit|Four|Ten|Boundary'){'B'}elseif($n-match 'Reject|Invalid|Missing|Wrong|Expired|Tampered|Unsafe|Error|Empty|Without|NonPositive'){'A'}else{'N'}}
function Expected($n){if($n-match 'Reject'){'Input is rejected with the expected error.'}elseif($n-match 'Accept'){'Input is accepted and required data is retained.'}elseif($n-match 'Return'){'Expected value or identifier is returned.'}elseif($n-match 'Create'){'Expected durable data is created exactly once.'}elseif($n-match 'Preserve'){'Existing identity is preserved safely.'}else{'All automated assertions pass.'}}
[xml]$doc=Get-Content -LiteralPath $TrxPath -Raw
$tests=@($doc.TestRun.Results.UnitTestResult|ForEach-Object{$full=[string]$_.testName;$p=$full.Split('.');$cls=$p[3];if(-not $map.Contains($cls)){throw "Missing report mapping: $cls"};[pscustomobject]@{Class=$cls;Code=$map[$cls][0];Function=$map[$cls][1];Scenario=$full.Substring($full.LastIndexOf('.')+1).Replace('_',' ');Expected=Expected $full;Type=Kind $full;Outcome=[string]$_.outcome}})
$excel=New-Object -ComObject Excel.Application;$excel.Visible=$false;$excel.DisplayAlerts=$false;$book=$null
try{
 $book=$excel.Workbooks.Open((Resolve-Path $WorkbookPath).Path);$keep=@('Guideline','Cover','Functions','Statistics','Example')
 for($i=$book.Worksheets.Count;$i-ge 1;$i--){$ws=$book.Worksheets.Item($i);if($keep -notcontains [string]$ws.Name){$ws.Delete()}}
 $example=$book.Worksheets.Item('Example');$groups=@($tests|Group-Object Class);$names=@()
 foreach($g in $groups){$example.Copy([Type]::Missing,$book.Worksheets.Item($book.Worksheets.Count));$s=$book.Worksheets.Item($book.Worksheets.Count);$first=$g.Group[0];$name=[string]$first.Code;$s.Name=$name;$names+=$name;$n=[int]$g.Count;$extra=[Math]::Max(0,$n-10);if($extra){$s.Rows.Item(('45:'+(44+$extra))).Insert()|Out-Null};$result=45+$extra
  $s.Range('C2').Value2='UT-'+$name;$s.Range('F2').Value2=[string]$first.Function;$s.Range('C3').Value2='IceBot Team';$s.Range('F3').Value2='Automated xUnit';$s.Range('C4').Value2='N/A';$s.Range('F4').Value2='0';$s.Range('C5').Value2='Unit tests for '+$first.Function+'.'
  $s.Range('A7').Value2=[double]@($g.Group|Where-Object Outcome -eq 'Passed').Count;$s.Range('C7').Value2=[double]@($g.Group|Where-Object Outcome -eq 'Failed').Count;$s.Range('F7').Value2=[double]0;$s.Range('L7').Value2=[double]@($g.Group|Where-Object Type -eq 'N').Count;$s.Range('M7').Value2=[double]@($g.Group|Where-Object Type -eq 'A').Count;$s.Range('N7').Value2=[double]@($g.Group|Where-Object Type -eq 'B').Count;$s.Range('O7').Value2=[double]$n
  $s.Range('F9:IV60').ClearContents();$s.Range('B14:D32').ClearContents();$s.Range(('B34:D'+(44+$extra))).ClearContents();$s.Range('B14').Value2='Test scenario';$s.Range('B33').Value2='Confirm';$s.Range('B34').Value2='Expected result'
  for($j=0;$j-lt $n;$j++){$c=6+$j;$t=$g.Group[$j];$s.Cells.Item(9,$c).Value2='UTCID'+($j+1).ToString('00');$s.Cells.Item(15+$j,4).Value2=[string]$t.Scenario;$s.Cells.Item(15+$j,$c).Value2='O';$s.Cells.Item(35+$j,4).Value2=[string]$t.Expected;$s.Cells.Item(35+$j,$c).Value2='O';$s.Cells.Item($result,$c).Value2=[string]$t.Type;$s.Cells.Item($result+1,$c).Value2=$(if($t.Outcome-eq'Passed'){'P'}else{'F'});$s.Cells.Item($result+2,$c).Value2=(Get-Date).ToString('MM/dd/yyyy')}
 }
 $f=$book.Worksheets.Item('Functions');$f.Range('A10:H200').ClearContents();for($i=0;$i-lt $names.Count;$i++){$g=@($tests|Where-Object Code -eq $names[$i])[0];$r=10+$i;$f.Cells.Item($r,1).Value2=[double]($i+1);$f.Cells.Item($r,5).Value2='UT-'+$g.Code;$f.Cells.Item($r,6).Value2=[string]$g.Function;$f.Cells.Item($r,7).Value2='Automated unit tests';$f.Cells.Item($r,8).Value2='No live hardware or BE required.'}
 $book.Save();$book.Close($true);$book=$null
}finally{if($book){try{$book.Close($false)}catch{}};try{$excel.Quit()}catch{};[GC]::Collect();[GC]::WaitForPendingFinalizers()}
"Rebuilt Unit Test workbook: $($tests.Count) tests in $($names.Count) sheets."
