param([Parameter(Mandatory=$true)][string]$TrxPath,[Parameter(Mandatory=$true)][string]$WorkbookPath)
$ErrorActionPreference='Stop'
$catalog=[ordered]@{
AuthenticationAndConnectivityTests=@('AUTH-NET','Authentication and NetBird validation');ConfigSetupWizardTests=@('CONFIG-ID','Configuration identity preservation');SiteSettingsTests=@('SITE-CFG','Site settings and device mapping');EdgeClientCertificateProvisionerTests=@('MTLS-CERT','mTLS client certificate');ExecutionEndpointRegistrationTests=@('ENDPOINT','Kiosk and execution endpoint contracts');PeripheralDeviceRegistrationTests=@('DEVICE','Peripheral device registration contract');EdgeDeploymentApiTests=@('DEPLOY-API','Full Edge deployment command contract');FullEdgeConfigurationInstallerTests=@('LUA-INSTALL','Verified Lua bundle installation');MachinePluginLoaderTests=@('DRIVER-DLL','Peripheral driver plugin loading');OrderRequestTests=@('LOCAL-ORDER','Legacy local Order contract');EdgeOrderInboxTests=@('MTLS-ORDER','mTLS ExecuteOrder validation');EdgeOrderExecutionQueueTests=@('ORDER-QUEUE','Durable production queue');ProductionReportOutboxTests=@('REPORT-OUT','Production report outbox')
}
function Expected([string]$n){if($n.Contains('Reject')){'Invalid or unsafe input is rejected with the expected error.'}elseif($n.Contains('Accept')){'Valid input is accepted and required data is retained.'}elseif($n.Contains('Return')){'The expected value or backend identifier is returned.'}elseif($n.Contains('Create')){'The expected durable object or file is created exactly once.'}elseif($n.Contains('Preserve')){'Existing backend identity is preserved safely.'}else{'All automated assertions pass.'}}
function TestType([string]$n){if($n-match 'Limit|Four|Ten|Boundary'){'B'}elseif($n-match 'Reject|Invalid|Missing|Wrong|Expired|Tampered|Unsafe|Error|Empty|Without|NonPositive'){'A'}else{'N'}}
[xml]$trx=Get-Content -LiteralPath $TrxPath -Raw
$items=@($trx.TestRun.Results.UnitTestResult|ForEach-Object{$full=$_.testName;$parts=$full.Split('.');$class=$parts[3];if(-not $catalog.Contains($class)){throw "Test class $class is missing from report catalog."};[pscustomobject]@{Class=$class;Code=$catalog[$class][0];Function=$catalog[$class][1];Scenario=$full.Substring($full.LastIndexOf('.')+1).Replace('_',' ');Expected=Expected $full;Type=TestType $full;Outcome=$_.outcome}})
$excel=New-Object -ComObject Excel.Application;$excel.Visible=$false;$excel.DisplayAlerts=$false
try{
 $book=$excel.Workbooks.Open((Resolve-Path $WorkbookPath).Path)
 $keep=@('Guideline','Cover','Functions','Statistics','Example')
 for($i=$book.Worksheets.Count;$i-ge 1;$i--){$s=$book.Worksheets.Item($i);if($keep -notcontains $s.Name){$s.Delete()}}
 $example=$book.Worksheets.Item('Example');$created=@()
 foreach($group in ($items|Group-Object Class)){
  $example.Copy([Type]::Missing,$book.Worksheets.Item($book.Worksheets.Count));$sheet=$book.Worksheets.Item($book.Worksheets.Count)
  $first=$group.Group[0];$sheet.Name=$first.Code.Substring(0,[Math]::Min(31,$first.Code.Length));$created+=$sheet.Name;$n=$group.Count
  if($n -gt 10){$sheet.Rows.Item('45:'+(44+$n-10)).Insert()|Out-Null}
  $sheet.Range('C2').Value2='UT-'+$first.Code;$sheet.Range('F2').Value2=$first.Function;$sheet.Range('C3').Value2='IceBot Team';$sheet.Range('F3').Value2='Automated xUnit';$sheet.Range('C4').Value2='N/A';$sheet.Range('F4').Value2=0;$sheet.Range('C5').Value2='Unit tests for '+$first.Function+'.'
  $sheet.Range('A7').Value2=@($group.Group|Where-Object Outcome -eq 'Passed').Count;$sheet.Range('C7').Value2=@($group.Group|Where-Object Outcome -eq 'Failed').Count;$sheet.Range('F7').Value2=0;$sheet.Range('L7').Value2=@($group.Group|Where-Object Type -eq 'N').Count;$sheet.Range('M7').Value2=@($group.Group|Where-Object Type -eq 'A').Count;$sheet.Range('N7').Value2=@($group.Group|Where-Object Type -eq 'B').Count;$sheet.Range('O7').Value2=$n
  $sheet.Range('F9:IV60').ClearContents();$sheet.Range('B14:D32').ClearContents();$sheet.Range('B34:D44').ClearContents();$sheet.Range('B14').Value2='Test scenario';$sheet.Range('B33').Value2='Confirm';$sheet.Range('B34').Value2='Expected result'
  for($j=0;$j-lt $n;$j++){ $col=6+$j;$t=$group.Group[$j];$sheet.Cells.Item(9,$col).Value2='UTCID'+($j+1).ToString('00');$sheet.Cells.Item(15+$j,4).Value2=$t.Scenario;$sheet.Cells.Item(15+$j,$col).Value2='O';$sheet.Cells.Item(35+$j,4).Value2=$t.Expected;$sheet.Cells.Item(35+$j,$col).Value2='O';$resultRow=45+[Math]::Max(0,$n-10);$sheet.Cells.Item($resultRow,$col).Value2=$t.Type;$sheet.Cells.Item($resultRow+1,$col).Value2=if($t.Outcome-eq'Passed'){'P'}else{'F'};$sheet.Cells.Item($resultRow+2,$col).Value2=(Get-Date).ToString('MM/dd/yyyy') }
 }
 $functions=$book.Worksheets.Item('Functions');$functions.Range('A10:H200').ClearContents();for($i=0;$i-lt $created.Count;$i++){$g=($items|Where-Object Code -eq $created[$i])[0];$r=10+$i;$functions.Cells.Item($r,1).Value2=$i+1;$functions.Cells.Item($r,5).Value2='UT-'+$g.Code;$functions.Cells.Item($r,6).Value2=$g.Function;$functions.Cells.Item($r,7).Value2='Automated unit tests';$functions.Cells.Item($r,8).Value2='No live hardware or BE required.'}
 $stats=$book.Worksheets.Item('Statistics');$stats.Range('A11:I100').ClearContents();for($i=0;$i-lt $created.Count;$i++){$group=@($items|Where-Object Code -eq $created[$i]);$r=11+$i;$stats.Cells.Item($r,1).Value2=$i+1;$stats.Cells.Item($r,2).Value2='UT-'+$created[$i];$stats.Cells.Item($r,3).Value2=@($group|Where-Object Outcome -eq 'Passed').Count;$stats.Cells.Item($r,4).Value2=@($group|Where-Object Outcome -eq 'Failed').Count;$stats.Cells.Item($r,5).Value2=0;$stats.Cells.Item($r,6).Value2=@($group|Where-Object Type -eq 'N').Count;$stats.Cells.Item($r,7).Value2=@($group|Where-Object Type -eq 'A').Count;$stats.Cells.Item($r,8).Value2=@($group|Where-Object Type -eq 'B').Count;$stats.Cells.Item($r,9).Value2=$group.Count}
 $book.Save();$book.Close($true)
}finally{if($book){[void][Runtime.InteropServices.Marshal]::ReleaseComObject($book)};try{$excel.Quit()}catch{};[void][Runtime.InteropServices.Marshal]::ReleaseComObject($excel);[GC]::Collect();[GC]::WaitForPendingFinalizers()}
Write-Output "Rebuilt Unit Test workbook: $($items.Count) tests in $($created.Count) function sheets."
