-- ============================================
-- Generated by FaiRobot Studio v1.0.3
-- Project Name : pre-review
-- Robot Model  : Fairino FR5 (6-DOF)
-- Active Tool  : None
-- Used Devices : bt_cup_l90, ice_cream
-- DEVICE_LIST  : ["bt_cup_l90:bt_cup_l90","ice_cream:ice_cream"]
-- Date         : 2026-08-15
-- Note         : Compatible with Fairino Controller LUA SDK
-- ============================================

-- Active Tool & Used Devices Definitions
local ACTIVE_TOOL_NAME = "None"
local USED_DEVICES = {"bt_cup_l90", "ice_cream"}

-- [Utility] Safe string-to-double converter.
local function toDouble(v)
    return tonumber(tostring(v)) + 0.0
end

-- [Bước 1] MoveJ - Điểm 1
MoveJ({toDouble("95.200"), toDouble("-71.900"), toDouble("127.800"), toDouble("-57.000"), toDouble("90.000"), toDouble("0.000")}, 0, 0, toDouble("30.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Bước 2] MoveJ - Điểm 2
MoveJ({toDouble("99.600"), toDouble("-63.900"), toDouble("95.600"), toDouble("-32.500"), toDouble("7.900"), toDouble("0.000")}, 0, 0, toDouble("30.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Bước 3] MoveJ - Điểm 3
MoveJ({toDouble("119.000"), toDouble("-54.000"), toDouble("70.000"), toDouble("-20.000"), toDouble("20.000"), toDouble("0.000")}, 0, 0, toDouble("30.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Bước 4] Kích hoạt bt_cup_l90
-- [Kích hoạt máy] Thiết bị: bt_cup_l90 | Lệnh: ON
-- TRIGGER_DEVICE: name="bt_cup_l90", command="ON"
TriggerDevice("bt_cup_l90", "ON")

-- [Bước 5] Delay 2s
WaitMs(2000)

-- [Bước 6] MoveJ - Điểm 4
MoveJ({toDouble("99.600"), toDouble("-63.900"), toDouble("95.600"), toDouble("-32.500"), toDouble("7.900"), toDouble("0.000")}, 0, 0, toDouble("30.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Bước 7] MoveJ - Điểm 5
MoveJ({toDouble("-92.000"), toDouble("-70.000"), toDouble("90.000"), toDouble("-25.000"), toDouble("158.000"), toDouble("0.000")}, 0, 0, toDouble("30.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Bước 8] Kích hoạt ice_cream
-- [Kích hoạt máy] Thiết bị: ice_cream | Lệnh: ON
-- TRIGGER_DEVICE: name="ice_cream", command="ON"
TriggerDevice("ice_cream", "ON")

-- [Bước 9] Delay 15s
WaitMs(15000)

-- [Bước 10] MoveJ - Điểm 6
MoveJ({toDouble("-78.000"), toDouble("-73.000"), toDouble("103.000"), toDouble("-28.000"), toDouble("100.000"), toDouble("0.000")}, 0, 0, toDouble("30.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Bước 11] MoveJ - Điểm 7
MoveJ({toDouble("-78.000"), toDouble("-61.000"), toDouble("109.000"), toDouble("-46.000"), toDouble("101.000"), toDouble("0.000")}, 0, 0, toDouble("30.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Bước 12] MoveJ - Điểm 8
MoveJ({toDouble("-78.000"), toDouble("-62.000"), toDouble("108.000"), toDouble("-29.000"), toDouble("99.000"), toDouble("0.000")}, 0, 0, toDouble("30.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Bước 13] MoveJ - Điểm 9
MoveJ({toDouble("-78.000"), toDouble("-92.000"), toDouble("108.000"), toDouble("23.000"), toDouble("99.000"), toDouble("0.000")}, 0, 0, toDouble("30.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- Kết thúc chương trình
