-- ============================================
-- Generated by FaiRobot Studio v1.0.3
-- Project Name : real-demo-1408
-- Robot Model  : Fairino FR5 (6-DOF)
-- Active Tool  : None
-- Used Devices : bt_cup_l90, icemachine
-- DEVICE_LIST  : ["bt_cup_l90:bt_cup_l90","icemachine:icemachine"]
-- Date         : 2026-08-14
-- Note         : Compatible with Fairino Controller LUA SDK
-- ============================================

-- Active Tool & Used Devices Definitions
local ACTIVE_TOOL_NAME = "None"
local USED_DEVICES = {"bt_cup_l90", "icemachine"}

-- [Utility] Safe string-to-double converter.
local function toDouble(v)
    return tonumber(tostring(v)) + 0.0
end

-- [Bước 1] MoveJ - Điểm 1
MoveJ({toDouble("94.900"), toDouble("-63.000"), toDouble("112.600"), toDouble("-52.500"), toDouble("94.900"), toDouble("4.800")}, 0, 0, toDouble("30.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Bước 2] MoveJ - Điểm 3
MoveJ({toDouble("99.600"), toDouble("-59.200"), toDouble("88.300"), toDouble("-29.500"), toDouble("7.900"), toDouble("0.100")}, 0, 0, toDouble("30.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Bước 3] MoveL - Điểm 7
MoveL({toDouble("403.800"), toDouble("-517.900"), toDouble("221.300"), toDouble("-87.400"), toDouble("81.600"), toDouble("176.500")}, 0, 0, toDouble("30.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Bước 4] Kích hoạt bt_cup_l90
-- [Kích hoạt máy] Thiết bị: bt_cup_l90 | Lệnh: ON
-- TRIGGER_DEVICE: name="bt_cup_l90", command="ON"
TriggerDevice("bt_cup_l90", "ON")

-- [Bước 5] Delay 2s
WaitMs(2000)

-- [Bước 6] MoveL - Điểm 4
MoveL({toDouble("194.600"), toDouble("-538.600"), toDouble("223.000"), toDouble("-88.200"), toDouble("88.300"), toDouble("177.900")}, 0, 0, toDouble("30.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Bước 7] MoveL - Điểm 6
MoveL({toDouble("131.000"), toDouble("550.000"), toDouble("239.300"), toDouble("-90.400"), toDouble("65.300"), toDouble("-179.800")}, 0, 0, toDouble("30.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Bước 8] Kích hoạt icemachine
-- [Kích hoạt máy] Thiết bị: icemachine | Lệnh: UP
-- TRIGGER_DEVICE: name="icemachine", command="UP"
TriggerDevice("ice_cream", "UP")

-- [Bước 9] Delay 11s
WaitMs(11000)

-- [Bước 10] MoveL - Điểm 6
MoveL({toDouble("-214.200"), toDouble("440.700"), toDouble("179.600"), toDouble("-92.900"), toDouble("-3.100"), toDouble("179.300")}, 0, 0, toDouble("30.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Bước 11] MoveL - Điểm 7
MoveL({toDouble("-218.700"), toDouble("466.200"), toDouble("64.100"), toDouble("-89.000"), toDouble("-3.000"), toDouble("-179.800")}, 0, 0, toDouble("30.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Bước 12] MoveL - Điểm 8
MoveL({toDouble("-209.400"), toDouble("414.700"), toDouble("53.900"), toDouble("-88.700"), toDouble("-4.100"), toDouble("-179.700")}, 0, 0, toDouble("30.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- Kết thúc chương trình
