-- ============================================
-- Generated by FaiRobot Studio v1.0.3
-- Project Name : real-demo-1408
-- Robot Model  : Fairino FR5 (6-DOF)
-- Active Tool  : None
-- Used Devices : bt_cup_l90
-- DEVICE_LIST  : ["bt_cup_l90:bt_cup_l90"]
-- Date         : 2026-08-14
-- Note         : Compatible with Fairino Controller LUA SDK
-- ============================================

-- Active Tool & Used Devices Definitions
local ACTIVE_TOOL_NAME = "None"
local USED_DEVICES = {"bt_cup_l90"}

-- [Utility] Safe string-to-double converter.
local function toDouble(v)
    return tonumber(tostring(v)) + 0.0
end

-- [Bước 1] MoveJ - Điểm 1
MoveJ({toDouble("94.900"), toDouble("-63.000"), toDouble("112.600"), toDouble("-52.500"), toDouble("94.900"), toDouble("4.800")}, 0, 0, toDouble("40.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Bước 2] MoveJ - Điểm 3
MoveJ({toDouble("99.600"), toDouble("-59.200"), toDouble("88.300"), toDouble("-29.500"), toDouble("7.900"), toDouble("0.100")}, 0, 0, toDouble("40.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Bước 3] MoveJ - Điểm 9
MoveJ({toDouble("119.000"), toDouble("-48.700"), toDouble("70.700"), toDouble("-23.100"), toDouble("20.600"), toDouble("0.100")}, 0, 0, toDouble("40.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Bước 4] Kích hoạt bt_cup_l90
-- [Kích hoạt máy] Thiết bị: bt_cup_l90 | Lệnh: ON
-- TRIGGER_DEVICE: name="bt_cup_l90", command="ON"
TriggerDevice("bt_cup_l90", "ON")

-- [Bước 5] Delay 2s
WaitMs(2000)

-- [Bước 6] MoveJ - Điểm 9
MoveJ({toDouble("99.600"), toDouble("-59.200"), toDouble("88.300"), toDouble("-29.500"), toDouble("7.900"), toDouble("0.100")}, 0, 0, toDouble("40.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Bước 7] MoveJ - Điểm 9
MoveJ({toDouble("-113.800"), toDouble("-61.000"), toDouble("88.500"), toDouble("-27.300"), toDouble("131.500"), toDouble("0.000")}, 0, 0, toDouble("40.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Bước 8] Delay 11s
WaitMs(11000)

-- [Bước 9] MoveJ - Điểm 9
MoveJ({toDouble("-76.100"), toDouble("-64.600"), toDouble("104.700"), toDouble("-37.200"), toDouble("100.800"), toDouble("0.000")}, 0, 0, toDouble("40.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Bước 10] MoveJ - Điểm 10
MoveJ({toDouble("-76.300"), toDouble("-51.100"), toDouble("104.400"), toDouble("-54.300"), toDouble("100.700"), toDouble("0.000")}, 0, 0, toDouble("40.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Bước 11] MoveJ - Điểm 11
MoveJ({toDouble("-75.900"), toDouble("-54.000"), toDouble("113.400"), toDouble("-60.700"), toDouble("100.000"), toDouble("0.000")}, 0, 0, toDouble("40.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- Kết thúc chương trình
